const collections = [
  {
    name: "Categories",
    urlKey: "categories",
    moduleName: "categories",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "name",
    defaultValues: {
      image: null,
      name: null,
      mainColor: null,
      fromColor: null,
      toColor: null,
      description: null,
      instructor: null,
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image",
        type: "Image",
      },
      {
        columnName: "Name",
        keyName: "name",
        width: "30%",
        type: "String",
      },
      {
        columnName: "Main color",
        keyName: "color",
        type: "String",
      },
      {
        columnName: "From Color",
        keyName: "fromColor",
        type: "String",
      },
      {
        columnName: "To Color",
        keyName: "toColor",
        tpe: "String",
      },
      // {
      //   columnName: "Instructor",
      //   keyName: "instructor",
      //   type: "Child",
      //   display: "name",
      // },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image",
        type: "Image",
        required: true,
        folder: "/categories/",
      },
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Main color",
        key: "color",
        type: "String",
        required: true,
      },
      {
        displayName: "From color",
        key: "fromColor",
        type: "String",
        required: true,
      },
      {
        displayName: "To color",
        key: "toColor",
        type: "String",
        required: true,
      },
      {
        displayName: "Instructor",
        key: "Instructor",
        collectionName: "instructor",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        required: true,
        multiline: true,
      },
    ],
  },
  {
    name: "Self-paced Courses",
    urlKey: "self-paced-courses",
    moduleName: "courses",
    filterBy: {
      key: "type",
      value: "SELF_PACED",
    },
    enableEdit: true,
    enableCreate: true,
    hasComingSoon: true,
    defaultSortParameter: "name",
    defaultValues: {
      image: null,
      name: null,
      description: null,
      category: null,
      assessment: null,
      instructor: null,
      goals: [],
      worksheets: [],
      modules: [],
      type: "SELF_PACED",
      isFree: false,
      product_id: null,
      reviews: [],
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image",
        type: "Image",
      },
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Category",
        keyName: "category",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Instructor",
        keyName: "instructor",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Assessment",
        keyName: "assessment",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Coming Soon",
        keyName: "coming_soon",
        type: "Boolean",
      },
      {
        columnName: "product id",
        keyName: "product_id",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image",
        type: "Image",
        required: true,
        folder: "/instructors/",
      },
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        multiline: true,
        required: true,
      },
      {
        displayName: "Is Free",
        key: "is_free",
        type: "Boolean",
      },
      {
        displayName: "Product id",
        key: "product_id",
        type: "String",
      },
      {
        displayName: "Price",
        key: "price",
        type: "Integer",
      },
      {
        displayName: "Type",
        key: "type",
        type: "Radio",
        required: true,
        values: [
          {
            key: "SELF_PACED",
            value: "Self Paced",
          },
          {
            key: "COHORT",
            value: "Cohort",
          },
        ],
      },
      {
        displayName: "Category",
        key: "category",
        collectionName: "categories",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Tags",
        key: "tags",
        collectionName: "tags",
        type: "ManyToManyReference",
        required: true,
      },
      {
        displayName: "Assessment",
        key: "assessment",
        collectionName: "assessments",
        type: "OneToOneReference",
      },
      {
        displayName: "Instructor",
        key: "instructor",
        collectionName: "instructor",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Goals",
        addLabel: "Add new Goal",
        key: "goals",
        type: "SyncList",
        required: true,
      },
      {
        displayName: "Worksheets",
        addLabel: "Add new worksheet",
        key: "worksheets",
        type: "SyncList",
        valueType: "Image",
        meta: {
          folder: "/courses/",
        },
        required: true,
      },
      {
        displayName: "Reviews",
        addLabel: "Add a new review",
        key: "Reviews",
        type: "SyncList",
        nested: true,
        required: true,
        headingKey: "review",
        defaultValues: {
          review: null,
          reviewer: null,
          reviewer_image: null,
        },
        inputFields: [
          {
            displayName: "Review",
            key: "review",
            type: "String",
            required: true,
          },
          {
            displayName: "Reviewer",
            key: "reviewer",
            type: "String",
            required: true,
          },
          {
            displayName: "Image",
            key: "reviewer_image",
            type: "Image",
            folder: "/reviews/",
          },
        ],
      },
      {
        name: "Modules",
        moduleName: "modules",
        displayName: "Modules",
        key: "modules",
        type: "ManyToOneReference",
        parentRefKey: "course",
        parentRefCollection: "courses",
        postDataPersistanceURL:
          "http://localhost:7000",
        getTitle: (doc) => {
          return doc && doc.title;
        },
        addButton: "Add Module",
        defaultValues: {
          video_url: null,
          video_thumbnail: null,
          title: null,
          description: null,
          tasks: [],
          isFree: false,
          worksheets: [],
        },
        inputFields: [
          {
            displayName: "Upload Video",
            key: "video_url",
            type: "Video",
            folder: "/modules/",
          },
          {
            displayName: "Video Thumbnail",
            key: "video_thumbnail",
            type: "Image",
            folder: "/modules/",
          },
          {
            displayName: "Upload Audio",
            key: "audio_url",
            type: "Video",
            folder: "/modules/",
          },
          {
            displayName: "Audio Thumbnail",
            key: "audio_thumbnail",
            type: "Image",
            folder: "/modules/",
          },
          {
            displayName: "Is free",
            key: "isFree",
            type: "Boolean",
          },
          {
            displayName: "Title",
            key: "title",
            type: "String",
            required: true,
          },
          {
            displayName: "Description",
            key: "description",
            type: "String",
          },
          {
            displayName: "Order",
            key: "order",
            type: "Integer",
            required: true,
          },
          {
            displayName: "Tasks",
            addLabel: "Add new task",
            key: "tasks",
            type: "SyncList",
            required: true,
          },
          {
            displayName: "Worksheets",
            addLabel: "Add new worksheet",
            key: "worksheets",
            type: "SyncList",
            valueType: "Image",
            meta: {
              folder: "/courses/",
            },
            required: true,
          },
        ],
      },
    ],
  },
  {
    name: "Cohort Courses",
    urlKey: "cohort-courses",
    moduleName: "courses",
    filterBy: {
      key: "type",
      value: "COHORT",
    },
    enableEdit: true,
    enableCreate: true,
    hasComingSoon: true,
    defaultSortParameter: "name",
    defaultValues: {
      image: null,
      name: null,
      description: null,
      category: null,
      assessment: null,
      instructor: null,
      goals: [],
      modules: [],
      rewards: [],
      worksheets: [],
      type: "COHORT",
      is_free: false,
      product_id: null,
      reviews: [],
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image",
        type: "Image",
      },
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Category",
        keyName: "category",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Instructor",
        keyName: "instructor",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Assessment",
        keyName: "assessment",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Product id",
        keyName: "product_id",
        type: "String",
      },
      {
        columnName: "Coming Soon",
        keyName: "coming_soon",
        type: "Boolean",
      },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image",
        type: "Image",
        required: true,
        folder: "/instructors/",
      },
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        multiline: true,
        required: true,
      },
      {
        displayName: "Type",
        key: "type",
        type: "Radio",
        required: true,
        values: [
          {
            key: "SELF_PACED",
            value: "Self Paced",
          },
          {
            key: "COHORT",
            value: "Cohort",
          },
        ],
      },
      {
        displayName: "Is Free",
        key: "is_free",
        type: "Boolean",
      },
      {
        displayName: "Product id",
        key: "product_id",
        type: "String",
      },
      {
        displayName: "Price",
        key: "price",
        type: "Integer",
      },
      {
        displayName: "Category",
        key: "category",
        collectionName: "categories",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Assessment",
        key: "assessment",
        collectionName: "assessments",
        type: "OneToOneReference",
      },
      {
        displayName: "Instructor",
        key: "instructor",
        collectionName: "instructor",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Goals",
        addLabel: "Add new Goal",
        key: "goals",
        type: "SyncList",
        required: true,
      },
      {
        displayName: "Rewards",
        addLabel: "Add reward image",
        key: "rewards",
        type: "SyncList",
        inputType: "Image",
        required: true,
      },
      {
        displayName: "Worksheets",
        addLabel: "Add new worksheet",
        key: "worksheets",
        type: "SyncList",
        valueType: "Image",
        meta: {
          folder: "/courses/",
        },
        required: true,
      },
      {
        displayName: "Reviews",
        addLabel: "Add a new review",
        key: "Reviews",
        type: "SyncList",
        nested: true,
        required: true,
        headingKey: "review",
        defaultValues: {
          review: null,
          reviewer: null,
          reviewer_image: null,
        },
        inputFields: [
          {
            displayName: "Review",
            key: "review",
            type: "String",
            required: true,
          },
          {
            displayName: "Reviewer",
            key: "reviewer",
            type: "String",
            required: true,
          },
          ,
          {
            displayName: "Image",
            key: "reviewer_image",
            type: "Image",
            folder: "/reviews/",
          },
        ],
      },
      {
        name: "Cohort batches",
        moduleName: "cohort-instances",
        displayName: "Cohort batches",
        key: "cohort-instances",
        type: "ManyToOneReference",
        parentRefKey: "course",
        parentRefCollection: "courses",
        addButton: "Add Batch",
        getTitle: (doc) => {
          if (!doc.from || !doc.to) return "Adding new batch";
          if (doc.from.toDate && doc.to.toDate) {
            return `${doc.from
              .toDate()
              .toDateString()} to ${doc.to.toDate().toDateString()}`;
          }
          if (doc.from.toDateString && doc.to.toDateString) {
            return `${doc.from.toDateString()} to ${doc.to.toDateString()}`;
          }
        },
        defaultValues: {
          from: null,
          to: null,
          total_slots: 0,
          whatsapp_link: null,
        },
        inputFields: [
          {
            displayName: "From date",
            key: "from",
            type: "Date",
          },
          {
            displayName: "To date",
            key: "to",
            type: "Date",
          },
          {
            displayName: "Total slots",
            key: "total_slots",
            type: "Integer",
          },
          {
            displayName: "Whatsapp link",
            key: "whatsapp_link",
            type: "String",
          },
        ],
      },
      {
        name: "Modules",
        moduleName: "modules",
        displayName: "Modules",
        key: "modules",
        type: "ManyToOneReference",
        parentRefKey: "course",
        parentRefCollection: "courses",
        postDataPersistanceURL:
          "http://localhost:7000/",
        getTitle: (doc) => {
          return doc && doc.title;
        },
        addButton: "Add Module",
        defaultValues: {
          video_url: null,
          video_thumbnail: null,
          title: null,
          description: null,
          tasks: [],
          isFree: false,
          worksheets: [],
        },
        inputFields: [
          {
            displayName: "Upload Video",
            key: "video_url",
            type: "Video",
            folder: "/modules/",
          },
          {
            displayName: "Video Thumbnail",
            key: "video_thumbnail",
            type: "Image",
            folder: "/modules/",
          },
          {
            displayName: "Upload Audio",
            key: "audio_url",
            type: "Video",
            folder: "/modules/",
          },
          {
            displayName: "Audio Thumbnail",
            key: "audio_thumbnail",
            type: "Image",
            folder: "/modules/",
          },
          {
            displayName: "Is free",
            key: "isFree",
            type: "Boolean",
          },
          {
            displayName: "Title",
            key: "title",
            type: "String",
            required: true,
          },
          {
            displayName: "Description",
            key: "description",
            type: "String",
          },
          {
            displayName: "Order",
            key: "order",
            type: "Integer",
            required: true,
          },
          {
            displayName: "Tasks",
            addLabel: "Add new task",
            key: "tasks",
            type: "SyncList",
            required: true,
          },
          {
            displayName: "Worksheets",
            addLabel: "Add new worksheet",
            key: "worksheets",
            type: "SyncList",
            valueType: "Image",
            meta: {
              folder: "/courses/",
            },
            required: true,
          },
        ],
      },
    ],
  },
  {
    name: "Instructors",
    urlKey: "instructors",
    moduleName: "instructor",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "name",
    defaultValues: {
      image: null,
      name: null,
      profession: null,
      designation: null,
      socialHandles: [],
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image",
        type: "Image",
      },
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Profession",
        keyName: "profession",
        type: "String",
      },
      {
        columnName: "Designation",
        keyName: "designation",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image",
        type: "Image",
        required: true,
        folder: "/instructors/",
      },
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Profession",
        key: "profession",
        type: "String",
        required: true,
      },
      {
        displayName: "Designation",
        key: "designation",
        type: "String",
        required: true,
      },
      {
        displayName: "Description",
        key: "intro",
        type: "String",
        required: true,
        multiline: true,
      },
      {
        displayName: "Social media handles",
        addLabel: "Add new social media handle",
        key: "socialHandles",
        type: "SyncList",
        nested: true,
        required: true,
        headingKey: "type",
        defaultValues: {
          type: null,
          url: null,
        },
        inputFields: [
          {
            displayName: "Media type",
            key: "type",
            type: "Select",
            choices: [
              {
                label: "Facebook",
                type: "FACEBOOK",
              },
              {
                label: "Twitter",
                type: "TWITTER",
              },
              {
                label: "Instagram",
                type: "INSTAGRAM",
              },
            ],
            required: true,
          },
          {
            displayName: "URL",
            key: "url",
            type: "String",
            required: true,
          },
        ],
      },
    ],
  },
  {
    name: "Authors",
    urlKey: "authors",
    moduleName: "author",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "name",
    defaultValues: {
      image: null,
      name: null,
      designation: null,
      description: null,
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image",
        type: "Image",
      },
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Designation",
        keyName: "designation",
        type: "String",
      },
      {
        columnName: "Description",
        keyName: "description",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image",
        type: "Image",
        required: true,
        folder: "/authors/",
      },
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Designation",
        key: "designation",
        type: "String",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        required: true,
        multiline: true,
      },
    ],
  },
  {
    name: "Videos",
    urlKey: "videos",
    moduleName: "videos",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "title",
    defaultValues: {
      title: null,
      length_in_mins: null,
      description: null,
      worksheets: [],
      tags: [],
    },
    columnOrder: [
      {
        columnName: "Thumbnail",
        keyName: "thumbnail",
        type: "Image",
      },
      {
        columnName: "Title",
        keyName: "title",
        type: "String",
      },
      {
        columnName: "Length",
        keyName: "length_in_mins",
        type: "String",
      },
      {
        columnName: "Description",
        keyName: "description",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Video",
        key: "url",
        type: "Video",
        required: true,
        folder: "/engage_videos/",
      },
      {
        displayName: "Thumbnail",
        key: "thumbnail",
        type: "Image",
        required: true,
        folder: "/engage_videos/",
      },
      {
        displayName: "Title",
        key: "title",
        type: "String",
        required: true,
      },
      {
        displayName: "Length",
        key: "length_in_mins",
        type: "Integer",
        required: true,
      },
      {
        displayName: "Tags",
        key: "tags",
        collectionName: "tags",
        type: "ManyToManyReference",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        required: true,
        multiline: true,
      },
      {
        displayName: "Worksheets",
        addLabel: "Add new worksheet",
        key: "worksheets",
        type: "SyncList",
        valueType: "Image",
        meta: {
          folder: "/videos/",
        },
        required: true,
      },
    ],
  },
  {
    name: "Assessments",
    urlKey: "assessments",
    moduleName: "assessments",
    enableEdit: true,
    enableCreate: true,
    dontShowRoute: true,
    defaultSortParameter: "name",
    defaultValues: {
      name: null,
    },
    exportData: true,
    reportingURL:
      "http://localhost:7000",
    columnOrder: [
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Category",
        keyName: "category",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Coming Soon",
        keyName: "coming_soon",
        type: "Boolean",
      },
    ],
  },
  {
    name: "Assessment Submissions",
    urlKey: "assessment-submissions",
    moduleName: "assessment-submissions",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "timestamp",
    defaultValues: {
      assessment_name: null,
    },
    columnOrder: [
      {
        columnName: "Assesement Name",
        keyName: "assessment_name",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Name",
        key: "assessment_name",
        type: "String",
        required: true,
      },
    ],
  },
  {
    name: "Book reviews",
    urlKey: "book-reviews",
    moduleName: "book-reviews",
    enableEdit: true,
    enableCreate: true,
    hasComingSoon: true,
    defaultSortParameter: "title",
    defaultValues: {
      image_url: null,
      title: null,
      category: null,
      subtitle: null,
      purchase_url: null,
      description: null,
      sections: [],
      isFree: false,
    },
    columnOrder: [
      {
        columnName: "Image",
        keyName: "image_url",
        type: "Image",
      },
      {
        columnName: "Title",
        keyName: "title",
        type: "String",
      },
      {
        columnName: "Subtitle",
        keyName: "subtitle",
        type: "String",
      },
      {
        columnName: "Purchase url",
        keyName: "purchase_url",
        type: "String",
      },
      {
        columnName: "Coming Soon",
        keyName: "coming_soon",
        type: "Boolean",
      },
      {
        columnName: "Category",
        keyName: "category",
        type: "Child",
        display: "name",
      },
      {
        columnName: "Is free",
        keyName: "isFree",
        type: "Boolean",
      },
    ],
    inputFields: [
      {
        displayName: "Image",
        key: "image_url",
        type: "Image",
        required: true,
        folder: "/book_reviews/",
      },
      {
        displayName: "Is free",
        key: "isFree",
        type: "Boolean",
      },
      {
        displayName: "Title",
        key: "title",
        type: "String",
        required: true,
      },
      {
        displayName: "Category",
        key: "category",
        collectionName: "categories",
        type: "OneToOneReference",
        required: true,
      },
      {
        displayName: "Subtitle",
        key: "subtitle",
        type: "String",
        required: true,
      },
      {
        displayName: "Purchase url",
        key: "purchase_url",
        type: "String",
        required: true,
      },
      {
        displayName: "Description",
        key: "description",
        type: "String",
        required: true,
        multiline: true,
      },
      {
        displayName: "Author",
        key: "authors",
        collectionName: "author",
        type: "ManyToManyReference",
        required: true,
      },
      {
        displayName: "Tags",
        key: "tags",
        collectionName: "tags",
        type: "ManyToManyReference",
        required: true,
      },
      {
        displayName: "Sections",
        addLabel: "Add new section",
        key: "sections",
        type: "SyncList",
        nested: true,
        required: true,
        headingKey: "title",
        defaultValues: {
          video_url: null,
          title: null,
          description: null,
          tasks: [],
        },
        inputFields: [
          {
            displayName: "Section title",
            key: "title",
            type: "String",
            required: true,
          },
          {
            displayName: "Section subtitle",
            key: "subtitle",
            type: "String",
            required: true,
          },
          {
            displayName: "Contents",
            addLabel: "Add new Content",
            key: "content",
            type: "SyncList",
            nested: true,
            required: true,
            headingKey: "text",
            defaultValues: {
              title: null,
              text: null,
            },
            inputFields: [
              {
                displayName: "Content title",
                key: "title",
                type: "String",
              },
              {
                displayName: "Content text",
                key: "text",
                type: "String",
                required: true,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Tags",
    urlKey: "tags",
    moduleName: "tags",
    enableEdit: true,
    enableCreate: true,
    defaultSortParameter: "name",
    defaultValues: {
      name: null,
      book_reviews: [],
      videos: [],
      courses: [],
    },
    columnOrder: [
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
    ],
    inputFields: [
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
    ],
  },
  {
    name: "User profiles",
    urlKey: "user-profiles",
    moduleName: "user-profiles",
    enableEdit: true,
    backendUrl: "http://localhost:7000",
    defaultValues: {
      name: null,
      is_admin: false,
      is_super_admin: false,
      phoneNumber: null,
    },
    columnOrder: [
      {
        columnName: "Name",
        keyName: "name",
        type: "String",
      },
      {
        columnName: "Email",
        keyName: "email",
        type: "String",
      },
      {
        columnName: "Phone Number",
        keyName: "phoneNumber",
        type: "String",
      },
      {
        columnName: "Is admin",
        keyName: "is_admin",
        type: "Boolean",
      },
      {
        columnName: "Has admin panel access",
        keyName: "is_super_admin",
        type: "Boolean",
      },
    ],
    inputFields: [
      {
        displayName: "Name",
        key: "name",
        type: "String",
        required: true,
      },
      {
        displayName: "Is admin",
        key: "is_admin",
        type: "Boolean",
      },
      {
        displayName: "Has admin panel access",
        key: "is_super_admin",
        type: "Boolean",
      },
    ],
  },
];

export default collections;
